---
title: "14.33 Final Paper Analysis"
output: html_notebook
---

```{r}
covid <- read.csv("analysis.csv")
original <- covid
```


```{r}
model <- lm(vaderPol ~ covidCases + stayathome_startday.14 + stayathome_startday.13 + stayathome_startday.12 + stayathome_startday.11 + stayathome_startday.10 + stayathome_startday.9 + stayathome_startday.8 + stayathome_startday.7 + stayathome_startday.6 + stayathome_startday.5 + stayathome_startday.4 + stayathome_startday.3 + stayathome_startday.2 + stayathome_startday.1 + stayathome_startday0 + stayathome_startday1 + stayathome_startday2 + stayathome_startday3 + stayathome_startday4 + stayathome_startday5 + stayathome_startday6 + stayathome_startday7 + stayathome_startday8 + stayathome_startday9 + stayathome_startday10 + stayathome_startday11 + stayathome_startday12 + stayathome_startday13 + stayathome_startday14, data=covid)

m1 = summary(model)
m1$coefficients[,1]/2*100
```



```{r}
model2 <- lm(pol ~ covidCases + stayathome_startday.14 + stayathome_startday.13 + stayathome_startday.12 + stayathome_startday.11 + stayathome_startday.10 + stayathome_startday.9 + stayathome_startday.8 + stayathome_startday.7 + stayathome_startday.6 + stayathome_startday.5 + stayathome_startday.4 + stayathome_startday.3 + stayathome_startday.2 + stayathome_startday.1 + stayathome_startday0 + stayathome_startday1 + stayathome_startday2 + stayathome_startday3 + stayathome_startday4 + stayathome_startday5 + stayathome_startday6 + stayathome_startday7 + stayathome_startday8 + stayathome_startday9 + stayathome_startday10 + stayathome_startday11 + stayathome_startday12 + stayathome_startday13 + stayathome_startday14, data=covid)


m2 = summary(model2)
m2$coefficients[,1]/2*100
```



```{r}
effects = c(model$coefficients[3:31])
seDown1 = effects - c(m1$coefficients[,2][3:31])
seUp1 = effects + c(m1$coefficients[,2][3:31])
effectsName = sprintf(100*effects/2, fmt="%1.2f%%")

effects2 = c(model2$coefficients[3:31])
seDown2 = effects2 - c(m2$coefficients[,2][3:31])
seUp2 = effects2 + c(m2$coefficients[,2][3:31])
effects2Name = sprintf(100*effects2/2, fmt="%1.2f%%")

days = c(-14:14)#c(-14:14)

plot(days, effects, main='Effect of COVID-19 Stay-at-Home Orders on Happiness (VADER)', xlab='Days Since Stay-at-Home Order Enforcement', ylab='Estimated Effect', type='o', ylim=c(-.015,.035))
abline(0, 0, lty=1)
abline(v=0, lty=2)
arrows(days, seUp1, days, seDown1, code=3, length=0.05, angle=90, col='red')
text(days, effects, labels=effectsName, cex=0.7, pos=c(1, 1, 3, 1, 3, 1, 3, 1, 1, 3, 1, 3, 3, 1, 1, 3, 3, 1, 3, 1, 3, 1, 1,3,3,1,1,3,1))

plot(days, effects2, main='Effect of COVID-19 Stay-at-Home Orders on Happiness (TextBlob)', xlab='Days Since Stay-at-Home Order Enforcement', ylab='Estimated Effect', type='o', ylim=c(-.015,.035))
abline(0, 0, lty=1)
abline(v=0, lty=2)
arrows(days, seUp2, days, seDown2, code=3, length=0.05, angle=90, col='red')
text(days, effects2, labels=effects2Name, cex=0.7, pos=c(3, 1, 1, 3, 1, 3, 1, 3, 3, 1, 1, 3, 1, 1, 1, 3, 1, 3, 1, 3, 3, 1, 1, 3, 1, 3, 3, 1,3))
```



```{r}
covid$vaderPol = (covid$vaderPol+1)/2*100
covid$pol = (covid$pol+1)/2*100

model3 <- lm(vaderPol ~ employment + outside, data=covid)

summary(model3)


model4 <- lm(pol ~ employment + outside, data=covid)

summary(model4)
```

